### ISSUE TITLE
综合-输出打印-沿路打印

### ISSUE THREAD

**Issue by shaohuixing** [shaohuixing/LYG#10]
沿路打印不成功：绘制路线后点击“打印”无响应

**Comment by remotesc2** [comment]
在家里试，出现这个提示
![image](https://cloud.githubusercontent.com/assets/9023036/9320912/05adeb84-4592-11e5-8107-32c34b2e18b0.png)
等待崔师傅...

**Comment by shaohuixing** [comment]
已正常
