### ISSUE TITLE
综合-输出打印-图幅输出

### ISSUE THREAD

**Issue by shaohuixing** [shaohuixing/LYG#12]
图幅输出失败：选择某一图幅后，点击“输出CAD”菜单，输出提示框响应很久，约20秒左右，后弹出CAD输出失败提示框。
![image](https://cloud.githubusercontent.com/assets/13741959/9197631/5a0e5c56-4068-11e5-8718-0293d6155bc3.png)

**Comment by remotesc2** [comment]
已解决，后台输出工具问题
