### ISSUE TITLE
外勤-计划分派

### ISSUE THREAD

**Issue by shaohuixing** [shaohuixing/LYG#31]
巡检计划的分派系统没有做任何限制：目前同一巡检计划可分派给多人，同时也可以无限制分派给同一巡检员很多次（分派一次即为一个巡检任务）。

**Comment by remotesc2** [comment]
sql语句里面对于是否已经存在的判断有问题，已修正

**Comment by shaohuixing** [comment]
同一巡检计划仍然能够多次分派给同一巡检员，app里“计划任务”会看到多条相同的巡检计划。

**Comment by shaohuixing** [comment]
多次分派及分派给多人是正常逻辑
