### ISSUE TITLE
外勤-计划管理

### ISSUE THREAD

**Issue by shaohuixing** [shaohuixing/LYG#40]
1、计划管理里面的计划分派列表以及计划总览列表中的属性列“制定人员”显示有问题，当前显示不是添加计划的人员名。
![image](https://cloud.githubusercontent.com/assets/13741959/9440026/97703c32-4a9e-11e5-85da-0c6091f123f7.png)
2、列表中的“是否需要反馈”列，貌似无意义（？？制定计划的“是否常规计划”有无关系？）

**Comment by remotesc2** [comment]
不知道为什么之前的代码写入的地方写死成了“8”。
已修正

**Comment by shaohuixing** [comment]
已验证
