### ISSUE TITLE
外勤-计划管理-制定计划-设备计划

### ISSUE THREAD

**Issue by shaohuixing** [shaohuixing/LYG#41]
在制定计划，选择设备计划，目前系统提供点击查询和条件查询，两种方式均查询不到设备。
![image](https://cloud.githubusercontent.com/assets/13741959/9440360/1be464aa-4aa1-11e5-9a70-df0a79de1d7d.png)

**Comment by shaohuixing** [comment]
目前条件查询界面根据范围查询可用，属性查询仍然不能用

**Comment by remotesc2** [comment]
问题出在text与val上
已修正

**Comment by shaohuixing** [comment]
设备查询-设置了查询条件进行查询，仍然不能查询到结果
