### ISSUE TITLE
外勤-巡检管理-巡检员监控

### ISSUE THREAD

**Issue by shaohuixing** [shaohuixing/LYG#47]
巡检员监控界面，对巡检员进行定位时，有的巡检员位置信息不对（均为维修科下的人员）
![image](https://cloud.githubusercontent.com/assets/13741959/9512014/ae95e52a-4caf-11e5-8a35-624477dcb224.png)

**Comment by remotesc2** [comment]
#47和#58是同一个问题导致的

**Comment by shaohuixing** [comment]
已验证
