### ISSUE TITLE
外勤-巡检管理-巡检员监控

### ISSUE THREAD

**Issue by shaohuixing** [shaohuixing/LYG#48]
此界面下巡检员事件查询无内容（事件查询主界面能够查询到）
![image](https://cloud.githubusercontent.com/assets/13741959/9512071/09918862-4cb0-11e5-8463-f7013527ae4e.png)

**Comment by remotesc2** [comment]
这里查询的是今日事件，已经把title改为“查询今日事件”
不属于bug

**Comment by shaohuixing** [comment]
已验证
