### ISSUE TITLE
外勤-工单管理-工单查询

### ISSUE THREAD

**Issue by shaohuixing** [shaohuixing/LYG#49]
对某一条工单进行“打印”操作，提示打印报表服务有误
![image](https://cloud.githubusercontent.com/assets/13741959/9512139/e2188172-4cb0-11e5-9793-4ede82ed5009.png)

**Comment by remotesc2** [comment]
之前缺少了一些“过程”
已修正

**Comment by shaohuixing** [comment]
已验证
