### ISSUE TITLE
综合-综合分析-纵剖面分析

### ISSUE THREAD

**Issue by shaohuixing** [shaohuixing/LYG#5]
纵剖面分析报错：选择起点和终点后，点击“分析”菜单。提示框返回-1.

**Comment by remotesc2** [comment]
![image](https://cloud.githubusercontent.com/assets/9023036/9321552/89845e68-459a-11e5-84ce-e765f2b7271d.png)

等待崔师傅

**Comment by remotesc2** [comment]
点表里缺少“高程”特征值
