### ISSUE TITLE
综合-废管管理-增加堵头

### ISSUE THREAD

**Issue by shaohuixing** [shaohuixing/LYG#51]
选中某一管线，增加堵头，右键“增加堵头”后，系统无响应，无后续操作菜单弹出。

**Comment by remotesc2** [comment]
之前获取“点设备”时写死了dname，但是dname在各个地方不一致，所以导致功能失效。
现在已经改为通过bs_prop（特征值）来获取“点设备”。
已修正

**Comment by baili666** [comment]
把常熟这边的更新一下吧，这个问题常熟也存在

**Comment by remotesc2** [comment]
常熟没有吧，我下午问过yaoshouguang

**Comment by shaohuixing** [comment]
已验证
