### ISSUE TITLE
综合-数据维护-合并点

### ISSUE THREAD

**Issue by shaohuixing** [shaohuixing/LYG#52]
合并点操作，点击查询点时不能查询到结果（用竖行菜单栏中的点击查询可以查询到改点的设备属性）
![image](https://cloud.githubusercontent.com/assets/13741959/9514440/a3d20494-4ccc-11e5-93c6-173d7bf87089.png)

**Comment by remotesc2** [comment]
原因：同#53的回答2

**Comment by shaohuixing** [comment]
已验证
