### ISSUE TITLE
综合-数据维护-延长管点到管段

### ISSUE THREAD

**Issue by shaohuixing** [shaohuixing/LYG#53]
1、延长管点到管段——是否标题应该改为延长管段到管点
![image](https://cloud.githubusercontent.com/assets/13741959/9514326/c20d6ddc-4ccb-11e5-919f-847ca8caec2c.png)
2、延长管点到管段，点选点设备时，查询不到结果（用竖行菜单栏的点击查询能够查询到该点设备属性）

**Comment by remotesc2** [comment]
1. 标题没有错，是这个意思
2. 点击查询只会查询在左边图例列表里选中的设备

**Comment by shaohuixing** [comment]
已验证
