### ISSUE TITLE
综合-数据维护-属性刷

### ISSUE THREAD

**Issue by shaohuixing** [shaohuixing/LYG#54]
用属性刷进行属性替换的时候会提示属性替换失败

**Comment by remotesc2** [comment]
valueArr的最后一个值不能是空字符串，为空的情况下服务便报错，已提给崔师傅

**Comment by remotesc2** [comment]
在fields增加了个gid，在values里增加了个0，保证不会以空结尾即可避免失败。
已修正

**Comment by shaohuixing** [comment]
已验证
