### ISSUE TITLE
综合分析-管网预警 

### ISSUE THREAD

**Issue by shaohuixing** [shaohuixing/LYG#6]
点击管网预警菜单，提示报错
![image](https://cloud.githubusercontent.com/assets/13741959/9195296/5f6794c4-4054-11e5-9029-8c6ba2a17c20.png)

**Comment by remotesc2** [comment]
缺少“维修次数”字段

**Comment by shaohuixing** [comment]
已增加“维修次数”字段，仍然弹出上述错误提示。

**Comment by remotesc2** [comment]
init.xml少配置了一条信息，已修正
