### ISSUE TITLE
综合-离线任务-添加

### ISSUE THREAD

**Issue by shaohuixing** [shaohuixing/LYG#66]
添加任务：点击“添加任务”，弹出任务制定窗口，输入任务名称和任务范围后点击“保存”，有时候鼠标太快点击了两次或三次，会导致添加多个‘相同’的任务。数据库属性中对于这样异常的任务除了gid不一致，其它属性均相同。

**Comment by remotesc2** [comment]
已优化此处逻辑，待测试
