### ISSUE TITLE
综合-离线任务-状态

### ISSUE THREAD

**Issue by shaohuixing** [shaohuixing/LYG#68]
对于已提交的任务，上传后审核，审核不同过的任务进行退回操作。移动端再次编辑上传后，离线任务栏改任务状态改变为已提交，但是状态栏对应的是审核，这导致退回的任务不能再次上传进行正确的审核操作。
![3](https://cloud.githubusercontent.com/assets/13741959/9755294/6e241bb6-5703-11e5-9b36-dbc67d097f4d.png)

**Comment by remotesc2** [comment]
不是问题，申请关闭，@shx
