### ISSUE TITLE
综合分析-废管管理

### ISSUE THREAD

**Issue by shaohuixing** [shaohuixing/LYG#7]
1、废管处理：查询后选择一目标数据点击“变为费管”，无成功提示菜单，废管处理不成功；
2、废管汇总统计无法正常结束，点击“废管汇总统计”对话框一直在统计中，约十分钟后弹出统计失败；
![image](https://cloud.githubusercontent.com/assets/13741959/9195614/abcd2994-4056-11e5-8eab-b4b25b293b3f.png)

**Comment by remotesc2** [comment]
1、家里需要19055ms
2、家里需要17ms
去现场再试试1
