### ISSUE TITLE
综合-离线任务-审核

### ISSUE THREAD

**Issue by shaohuixing** [shaohuixing/LYG#70]
HopeCAD编辑任务提交后，点击“审核”进入审核页面，在管网数据列表中双击某一数据，弹出审核意见框，在对话框中输入审核意见后，点击“审核意见”栏目进行查看，查询不到提交的审核意见。
![image](https://cloud.githubusercontent.com/assets/13741959/9849210/327cc5ec-5b1b-11e5-9872-84a929dcf9f2.png)

**Comment by remotesc2** [comment]
已修正
不知道为什么后台代码变动了，前台代码没有相应做修改

**Comment by shaohuixing** [comment]
已验证
