### ISSUE TITLE
综合-输出打印-栓点打印

### ISSUE THREAD

**Issue by shaohuixing** [shaohuixing/LYG#9]
栓点打印时，点选设备时弹出的浮云需要修改，目前的浮云框看起来像是报错浮云。
![image](https://cloud.githubusercontent.com/assets/13741959/9195999/bf38c346-4059-11e5-93b6-c9a7d1b40e71.png)

**Comment by remotesc2** [comment]
已修改为此效果
![image](https://cloud.githubusercontent.com/assets/9023036/9214568/106ad93e-40d2-11e5-8a5a-cf19400fbde2.png)
